apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 8190
          volumeMounts:
          - name: {{ .Values.volumeMount.name }}
            mountPath: {{ .Values.volumeMount.mountPath }}
      volumes:
        - name: {{ .Values.volumeMount.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumeMount.claimName }}
